function defineShapeMesh()
	return {
		class="ShapeMesh",
		arrays=
		{
			{
				{
					attribute=
					{
						name="position",
						dataType="TYPE_FLOAT",
						numComponents=2,
						usage="USAGE_POSITION",
					},
					-- offset and stride are automatically computed
				},
				{
					attribute=
					{
						name="colour",
						dataType="TYPE_FLOAT",
						numComponents=4,
						usage="USAGE_COLOUR",
					},
				},
				{
					attribute=
					{
						name="texcoord",
						dataType="TYPE_FLOAT",
						numComponents=2,
						usage="USAGE_TEXCOORD",
					},
				},
			},
		},
		indexArray=
		{
			dataType="TYPE_UINT16",
		},
	}
end
